<div class="megamenu-panel multi-tier" id="megamenu-expertise" data-target="research">
  <div class="bg row"></div>
  <div class="fg row">
    <div class="col-md-3 mm-tier tier-1 mm-left">
      <ul class="mm-menu active">
        <li class="parent" data-label="centers-and-institutes" data-parent="centers-and-institutes">
          <a rel="page" href="/research/centers-institutes/">Centers and Institutes</a>
        </li>
        <li class="parent" data-label="clinical-research" data-parent="clinical-research">
          <a rel="page" href="/research/clinical/">Clinical Research</a>
        </li>
        <li class="parent" data-label="faculty" data-parent="faculty">
          <a rel="page" href="/research/faculty-labs/">Faculty Labs</a>
        </li>
        <li class="parent" data-label="training-programs" data-parent="training-programs">
          <a rel="page" href="/research/training-programs/">Training Programs</a>
        </li>
        <li class="parent" data-label="investigator-support" data-parent="investigator-support">
          <a rel="12464" href="/research/support/">Investigator Support</a>
        </li>
        <li class="parent" data-label="service-cores" data-parent="service-cores">
          <a rel="page" href="/research/service-cores/">Service Cores</a>
        </li>
      </ul>
    </div>
    <div class="col-md-9 mm-tier tier-2 mm-right">
      <div class="expertise-detail active" data-label="centers-and-institutes">
        <span class="menu-header">Centers and Institutes</span>
        <div class="summary">
          <p>IU School of Medicine centers and institutes support highly collaborative basic, clinical and translational research on a broad range of scientific, medical and health care topics, including cancer, genomic medicine, diabetes, Alzheimer’s disease, traumatic brain injury, bone and stem cell biology, and health outcomes.</p>
        </div>
        
        <div class="row">
          <div class="col-md-6">
            <ul class="mm-menu active">

              <li data-label="computational-biology-bioinformatics">
                <a rel="page" href="/research/centers-institutes/computational-biology-bioinformatics/">Bioinformatics</a>
              </li>

              <li data-label="breast-cancer">
                <a rel="page" href="/research/centers-institutes/breast-cancer/">Breast Cancer</a>
              </li>
              <li data-label="cancer">
                <a rel="page" href="/research/centers-institutes/cancer/">Cancer</a>
              </li>

              <li data-label="diabetes-metabolic-diseases">
                <a rel="page" href="/research/centers-institutes/diabetes-metabolic-diseases/">Diabetes</a>
              </li>
        
              <li data-label="immunotherapy">
                <a rel="page" href="/research/centers-institutes/immunotherapy/">Immunotherapy</a>
              </li>
              
              


            </ul>
          </div>
          <div class="col-md-6">
            <ul class="mm-menu">

              <li data-label="CTSI">
                <a rel="page" href="https://indianactsi.org/" target="_blank">Indiana CTSI</a>
              </li>
              
              <li data-label="musculoskeletal-health">
                <a rel="page" href="/research/centers-institutes/musculoskeletal-health/">Musculoskeletal Health</a>
              </li>


              <li data-label="stark-neurosciences">
                <a rel="page" href="/research/centers-institutes/stark-neurosciences/">Neurosciences</a>
              </li>

              <li data-label="pediatrics">
                <a rel="page" href="/research/centers-institutes/wells-pediatric-research/">Pediatric Research</a>
              </li>   

              <li data-label="regenerative-medicine">
                <a rel="page" href="/research/centers-institutes/regenerative-medicine-and-engineering/">Regenerative Medicine </a>
              </li>              
          

            </ul>
          </div>      
          
        </div>
      </div>
        <!-- end of centers -->

      <div class="expertise-detail" data-label="clinical-research">
        <span class="menu-header">Clinical Research</span>
        <div class="summary">
          <p>At IU School of Medicine, physicians across every medical specialty are advancing detection and treatment through clinical trials and related studies. Patients interested in finding a clinical trial can explore the full list of clinical trials available through IU School of Medicine.</p>
        </div>

        <div class="row">
          <div class="col-md-6">
            <ul class="mm-menu" data-label="faculty">
              <li data-label="clinical-research.trials">
                <a rel="page" href="/research/clinical/trials/">Clinical Trials</a>
              </li>
              <li data-label="clinical-research.health">
                <a rel="page" href="/research/clinical/health-policy-professionalism-research/">Health Policy and Professionalism Research</a>
              </li>
              <li data-label="clinical-research.vitro">
                <a rel="page" href="/research/clinical/in-vitro/">In Vitro Diagnostics Development and Clinical Trials</a>
              </li>            
            </ul>
          </div>  

        


        </div>
      </div>
      <!-- end of clinical  -->
      <div class="expertise-detail" data-label="faculty">
        <span class="menu-header">Faculty Labs</span>
        <div class="summary">
          <p>Faculty investigators throughout IU School of Medicine’s 26 academic departments work together to advance knowledge and treatment for patients in the world’s most critical areas of medicine. </p>
        </div>
      </div>
      
      <!-- end of faculty -->
      <div class="expertise-detail" data-label="training-programs">
        <span class="menu-header">Training Programs</span>
        <div class="summary">
          <p>Indiana University School of Medicine offers many excellent research training and internship programs for high school, pre-med, medical and post-graduate students interested in exploring medical and health-related research work.</p>
        </div>
        <div class="row">
          <div class="col-md-6">
            <li data-label="training-programs.physician-scientists">
              <a rel="page" href="/research/training-programs/physician-scientists-engineers/">Physician-Scientists and Physician-Engineers</a>
            </li>
            <li data-label="training-programs.musculoskeletal-biology">
              <a rel="page" href="/research/training-programs/musculoskeletal-biology/">Musculoskeletal Biology</a>
            </li>
          </div>
          <div class="col-md-6">
            <li data-label="training-programs.postdoctoral">
              <a rel="page" href="/research/training-programs/postdoctoral/">Postdoctoral Training</a>
            </li>
            <li data-label="training-programs.biomedical-sciences">
              <a rel="page" href="/research/training-programs/biomedical-sciences/">Biomedical Sciences</a>
            </li>            
          </div>
          
        </div>
        
        
      </div>

      <div class="expertise-detail" data-label="investigator-support">
        <span class="menu-header">Investigator Support</span>
        <div class="summary">
          <p>Through the Office of Research Administration, IU School of Medicine provides support resources to help investigators access information and tools necessary to conduct successful research programs. Services include grant administration and reporting support, fiscal compliance guidance and more.</p>
        </div>
        <div class="row">
          <div class="col-md-6">
            <li data-label="investigator-support.research-connect">
              <a rel="page" href="/research/support/research-connect/">ReSEARCH Connect FAQ</a>
            </li>
            <li data-label="investigator-support.research-connect">
              <a rel="page" href="/research/support/contacts/">Contacts</a>
            </li>
            </li>
          </div>
       
        </div>
      </div>

      <div class="expertise-detail" data-label="service-cores">
        <span class="menu-header">Service Cores</span>
        <div class="summary">
          <p>Service core laboratories provide medical researchers with specialized scientific services to support their studies.</p>
        </div>
        <div class="row">
          <div class="col-md-6">
            <li data-label="service-cores.histology-core">
              <a rel="page" href="/research/service-cores/histology/">Histology Core</a>
            </li>
            <li data-label="service-cores.imaging-and-flow">
              <a rel="page" href="/research/service-cores/imaging-flow-cytometry/">Imaging and Flow Cytometry</a>
            </li>
            <li data-label="service-cores.immunohistochemistry">
              <a rel="page" href="/research/service-cores/immunohistochemistry/">Immunohistochemistry Core</a>
            </li>
                
          </div>
          <div class="col-md-6">
            <li data-label="service-cores.medical-genomics">
              <a rel="page" href="/research/service-cores/medical-genomics/">Medical Genomics</a>
            </li>
            <li data-label="service-cores.micro-computed-tomography-center">
              <a rel="page" href="/research/service-cores/micro-computed-tomography-center/">Micro Computed Tomography Center</a>
            </li>
            <li data-label="service-cores.electron-microscopy">
              <a rel="page" href="/research/service-cores/electron-microscopy/">Electron Microscopy Core</a>
            </li>
            <li data-label="service-cores.research-imaging">
              <a rel="page" href="/research/service-cores/research-imaging/">Research Imaging</a>
            </li>
            
          </div>
          
        </div>
        
      </div>

      </div>
    </div>


</div>