<div class="megamenu-panel" id="megamenu-departments" data-target="departments">
	<div class="bg row"></div>
	<div class="fg row">
		<div class="col-md-4 mm-left">
			<h2 class="menu-header">Basic Science</h2>
			<div class="pane">
				<ul class="arrow-bullets">
					<li><a href="/departments/anatomy-cell-biology/">Anatomy and Cell Biology</a></li>
					<li><a href="/departments/biochemistry-molecular-biology/">Biochemistry and Molecular Biology</a></li>
					<li><a href="/departments/biostatistics/">Biostatistics</a></li>
					<li><a href="/departments/physiology/">Cellular and Integrative Physiology</a></li>
					<li><a href="/departments/microbiology-immunology/">Microbiology and Immunology</a></li>
					<li><a href="/departments/pharmacology-toxicology/">Pharmacology and Toxicology</a></li>
				</ul>
			</div>
		</div>
		<div class="col-md-8 mm-right">
			<h2 class="menu-header">Clinical Science</h2>
			<div class="pane row">
				<div class="col-md-6">
					<ul class="arrow-bullets">
						<li><a href="/departments/anesthesia/">Anesthesia</a></li>
						<li><a href="/departments/dermatology/">Dermatology</a></li>
						<li><a href="/departments/emergency-medicine/">Emergency Medicine</a></li>
						<li><a href="/departments/family-medicine/">Family Medicine</a></li>
   					<li><a href="/departments/genetics/">Medical and Molecular Genetics</a></li>
						<li><a href="/departments/internal-medicine/">Medicine</a></li>
						<li><a href="/departments/neurological-surgery/">Neurological Surgery</a></li>
						<li><a href="/departments/neurology/">Neurology</a></li>
						<li><a href="/departments/obgyn/">Obstetrics and Gynecology</a></li>
						<li><a href="/departments/ophthalmology/">Ophthalmology</a></li>
          	<li><a href="/departments/pathology/">Pathology and Laboratory Medicine</a></li>
					</ul>
				</div>
				<div class="col-md-6">
					<ul class="arrow-bullets">
						<li><a href="/departments/orthopaedic-surgery/">Orthopaedic Surgery</a></li>
						<li><a href="/departments/otolaryngology/">Otolaryngology</a></li>
						<li><a href="/departments/pediatrics/">Pediatrics</a></li>
						<li><a href="/departments/physiatry/">Physical Medicine and Rehabilitation</a></li>
						<li><a href="/departments/psychiatry/">Psychiatry</a></li>
						<li><a href="/departments/radiology/">Radiology and Imaging Sciences</a></li>
						<li><a href="/departments/radiation-oncology/">Radiation Oncology</a></li>
						<li><a href="/departments/surgery/">Surgery</a></li>
						<li><a href="/departments/urology/">Urology</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>

