<div class="megamenu-panel multi-tier" id="megamenu-education" data-target="education">
	<div class="bg row"></div>
	<div class="fg row">

		<div class="col-md-3 mm-tier tier-1">
			<ul class="mm-menu active">
				<li data-label="md"><a rel="page" href="/education/md/">MD Program</a></li>
				<!--<li data-label="campuses" class="active"><a rel="page" href="/education/campuses/">Statewide Campuses</a></li>-->
				<li data-label="gme"><a rel="page" href="/education/gme/">Graduate Medical Education</a></li>
				<li data-label="graduate-degrees"><a rel="page" href="/education/graduate-degrees/">Graduate Degrees</a></li>
				<li data-label="undergraduate-health-professions"><a rel="page" href="/education/undergraduate-health-professions/">Health Professions Programs</a></li>				
				<li data-label="cme"><a rel="page" href="/education/cme/">Continuing Medical Education</a></li>
				<li data-label="medical-library"><a rel="page" href="/education/medical-library/">Medical Library</a></li>
				<li data-label="mhs"><a target="_blank" rel="12468" href="/education/mental-health-services/">Mental Health Services</a></li>
			</ul>
		</div>

		<div class="col-md-3 mm-tier tier-2">

			<ul class="mm-menu" data-label="campuses">
				<li data-label="indianapolis"><a rel="page" href="/education/campuses/indianapolis/">Indianapolis</a></li>
				<li data-label="bloomington" class="active"><a rel="page" href="/education/campuses/bloomington/">Bloomington</a></li>
				<li data-label="evansville"><a rel="page" href="/education/campuses/evansville/">Evansville</a></li>
				<li data-label="fort-wayne"><a rel="page" href="/education/campuses/fort-wayne/">Fort Wayne</a></li>
				<li data-label="muncie"><a rel="page" href="/education/campuses/muncie/">Muncie</a></li>
				<li data-label="gary"><a rel="page" href="/education/campuses/gary/">Northwest – Gary</a></li>
				<li data-label="south-bend"><a rel="page" href="/education/campuses/south-bend/">South Bend</a></li>
				<li data-label="terre-haute"><a rel="page" href="/education/campuses/terre-haute/">Terre Haute</a></li>
				<li data-label="west-lafayette"><a rel="page" href="/education/campuses/west-lafayette/">West Lafayette</a></li>
			</ul>

			<ul class="mm-menu active" data-label="md">
				<li data-label="md.admissions"><a rel="page" href="/education/md/admissions/">MD Admissions</a></li>				
				<li data-label="md.curriculum"><a rel="page" href="/education/md/curriculum/">Curriculum</a></li>
				<li data-label="md.dual-degrees"><a rel="page" href="/education/md/dual-degrees/">Dual Degrees</a></li>
				<li data-label="md.residency-placement"><a rel="page" href="/education/md/residency-placement/">Residency Placement</a></li>
				<li data-label="md.student-support"><a rel="page" href="/education/md/student-support/">Student Support</a></li>
				<li data-label="md.tuition"><a rel="page" href="/education/md/tuition/">Tuition and Fees</a></li>
				<li data-label="md.service-learning"><a rel="page" href="/education/service-learning/">Service Learning</a></li>
				<li data-label="md.technical-standards"><a rel="page" href="/education/md/technical-standards/">Technical Standards</a></li>
				<li data-label="md.lcme-accreditation"><a rel="page" href="/education/md/lcme-accreditation/">LCME Accreditation</a></li>
			</ul>

            <ul class="mm-menu" data-label="gme">
                <li data-label="residency-programs"><a rel="page" href="/education/gme/residency-programs/">Residency Programs</a></li>
                <li data-label="fellowship-programs"><a rel="page" href="/education/gme/fellowship-programs/">Fellowship Programs</a></li>
                <li data-label="accreditation"><a rel="page" href="/education/gme/accreditation/">ACGME Accreditation</a></li>
                <li data-label="employment-terms-benefits"><a rel="page" href="/education/gme/employment-terms-benefits/">Employment Terms and Benefits</a></li>
                <li data-label="enrollment-orientation"><a rel="page" href="/education/gme/enrollment-orientation/">Enrollment and Orientation</a></li>
                <li data-label="contacts"><a rel="page" href="/education/gme/contacts/">Contacts</a></li>
            </ul>

			<ul class="mm-menu" data-label="graduate-degrees">
                <li data-label="phd-programs"><a rel="page" href="/education/graduate-degrees/phd/">PhD</a></li>
                <li data-label="masters-degrees"><a rel="page" href="/education/graduate-degrees/masters/">Masters</a></li>
                <li data-label="certificates"><a rel="page" href="/education/graduate-degrees/certificates/">Certificates</a></li>
                <li data-label="lgrad-programs"><a rel="page" href="/education/graduate-degrees/lgrad/">LGRAD</a></li>
				<li data-label="mstp"><a rel="page" href="/education/graduate-degrees/postdoctoral/">Postdoctoral</a></li>
				<li data-label="education-phd-track"><a rel="page" href="/education/graduate-degrees/scholarships/">Scholarships</a></li>
                <li data-label="education-phd-track"><a rel="page" href="/education/graduate-degrees/contacts/">Contacts</a></li>
			</ul>
			
			<ul class="mm-menu" data-label="medical-library">
				<li data-label="medical-library.visits"><a rel="page" href="/education/medical-library/visit/">Visit</a></li>
				<li data-label="medical-library.services"><a rel="page" href="/education/medical-library/services/">Services</a></li>
				<li data-label="medical-library.policies"><a rel="page" href="/education/medical-library/policies/">Policies</a></li>
				<li data-label="medical-library.giving"><a rel="page" href="/education/medical-library/giving/">Giving</a></li>
				<li data-label="medical-library.events"><a rel="page" href="/education/medical-library/events/">Events</a></li>
				<li data-label="medical-library.history-of-medicine"><a rel="page" href="/education/medical-library/history-of-medicine/">History of Medicine</a></li>
			</ul>
			
			<ul class="mm-menu" data-label="undergraduate-health-professions">
				<li data-label="degrees"><a rel="page" href="/education/undergraduate-health-professions/degrees/">Degrees</a></li>
				<li data-label="certificates"><a rel="page" href="/education/undergraduate-health-professions/certificates/">Certificates</a></li>
				<li data-label="course-basic-emt"><a rel="page" href="/education/undergraduate-health-professions/course-basic-emt/">Courses</a></li>
				<li data-label="admissions"><a rel="page" href="/education/undergraduate-health-professions/admissions/">Admissions</a></li>
				<li data-label="student-support"><a rel="page" href="/education/undergraduate-health-professions/student-support/">Student Support</a></li>
				<li data-label="contacts"><a rel="page" href="/education/undergraduate-health-professions/contacts/">Contacts</a></li>
			</ul>
			
			<ul class="mm-menu" data-label="cme">
                <li data-label="maintenance-of-certification"><a rel="page" href="/education/cme/maintenance-of-certification/">Maintenance of Certification</a></li>
                <li data-label="faculty-presenters"><a rel="page" href="/education/cme/faculty-presenters/">Faculty Presenters</a></li>
                <li data-label="plan"><a rel="page" href="/education/cme/plan/">Plan an Activity</a></li>
                <li data-label="partners"><a rel="page" href="/education/cme/partners/">Partnerships</a></li>

        <li data-label="contacts"><a rel="page" href="/education/cme/contacts/">Contacts</a></li>
            </ul>
			
		</div>

		<div class="col-md-6 mm-tier tier-3">

			<div class="campus-detail" data-label="bloomington">
				<span class="menu-header">Bloomington</span>
				<div class="summary">
					<p>The Medical Sciences Program in Bloomington is unique among the IU School of Medicine campuses in that it educates medical students seeking an MD as well as graduate and undergraduate students. Bloomington offers a Big 10 learning environment on an iconic campus.</p>
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="campus-life"><a rel="page" href="/education/campuses/bloomington/campus-life/">Campus Life</a></li>
							<li data-label="md-program"><a rel="page" href="/education/campuses/bloomington/md-program/">MD Program</a></li>
							<li data-label="graduate-programs"><a rel="page" href="/education/campuses/bloomington/graduate-programs/">Graduate Programs</a></li>
							<li data-label="undergraduate-programs"><a rel="page" href="/education/campuses/bloomington/undergraduate-programs/">Undergraduate Programs</a></li>
							<li data-label="student-support"><a rel="page" href="/education/campuses/bloomington/student-support/">Student Services</a></li>
							<li data-label="service-learning"><a rel="page" href="/education/campuses/bloomington/service-learning/">Service Learning</a></li>
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="research"><a rel="page" href="/education/campuses/bloomington/research/">Research</a></li>
							<li data-label="faculty"><a rel="page" href="/education/campuses/bloomington/faculty/">Faculty</a></li>
							<li data-label="giving"><a rel="page" href="/education/campuses/bloomington/giving/">Giving</a></li>
							<li data-label="clinical-partners"><a rel="page" href="/education/campuses/bloomington/clinical-partners/">Clinical Partners</a></li>
							<li data-label="news-events"><a rel="page" href="/education/campuses/bloomington/news-events/">News and Events</a></li>
							<li data-label="contacts"><a rel="page" href="/education/campuses/bloomington/contacts/">Contacts</a></li>
						</ul>
					</div>
				</div>
			</div>

			<div class="campus-detail" data-label="evansville">
				<span class="menu-header">Evansville</span>
				<div class="summary">
					<p>With six major hospitals housing about 2000 beds, medical students in Evansville have access to physician educators in a range of medical specialties. An expanded residency program here will provide more than 100 new graduate medical education positions over the next few years.</p>
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="campus-life"><a rel="page" href="/education/campuses/evansville/campus-life/">Campus Life</a></li>
							<li data-label="md-program"><a rel="page" href="/education/campuses/evansville/md-program/">MD Program</a></li>
							<li data-label="student-support"><a rel="page" href="/education/campuses/evansville/student-support/">Student Services</a></li>
							<li data-label="service-learning"><a rel="page" href="/education/campuses/evansville/service-learning/">Service Learning</a></li>
							<li data-label="research"><a rel="page" href="/education/campuses/evansville/research/">Research</a></li>
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="faculty"><a rel="page" href="/education/campuses/evansville/faculty/">Faculty</a></li>
							<li data-label="giving"><a rel="page" href="/education/campuses/evansville/giving/">Giving</a></li>
							<li data-label="clinical-partners"><a rel="page" href="/education/campuses/evansville/clinical-partners/">Clinical Partners</a></li>
							<li data-label="news-events"><a rel="page" href="/education/campuses/evansville/news-events/">News and Events</a></li>
							<li data-label="contacts"><a rel="page" href="/education/campuses/evansville/contacts/">Contacts</a></li>
						</ul>
					</div>
				</div>
			</div>

			<div class="campus-detail" data-label="fort-wayne">
				<span class="menu-header">Fort Wayne</span>
				<div class="summary">
					<p>The Fort Wayne campus offers clinical education in both rural and urban communities through two large hospital systems serving the region. A Student Research Fellowship Program offers med students nine weeks of summer research experience.</p>
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="campus-life"><a rel="page" href="/education/campuses/fort-wayne/campus-life/">Campus Life</a></li>
							<li data-label="md-program"><a rel="page" href="/education/campuses/fort-wayne/md-program/">MD Program</a></li>
							<li data-label="student-support"><a rel="page" href="/education/campuses/fort-wayne/student-support/">Student Services</a></li>
							<li data-label="service-learning"><a rel="page" href="/education/campuses/fort-wayne/service-learning/">Service Learning</a></li>
							<li data-label="research"><a rel="page" href="/education/campuses/fort-wayne/research/">Research</a></li>
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="faculty"><a rel="page" href="/education/campuses/fort-wayne/faculty/">Faculty</a></li>
							<li data-label="giving"><a rel="page" href="/education/campuses/fort-wayne/giving/">Giving</a></li>
							<li data-label="clinical-partners"><a rel="page" href="/education/campuses/fort-wayne/clinical-partners/">Clinical Partners</a></li>
							<li data-label="news-events"><a rel="page" href="/education/campuses/fort-wayne/news-events/">News and Events</a></li>
							<li data-label="contacts"><a rel="page" href="/education/campuses/fort-wayne/contacts/">Contacts</a></li>
						</ul>
					</div>
				</div>
			</div>
			
			<div class="campus-detail" data-label="indianapolis">
				<span class="menu-header">Indianapolis</span>
				<div class="summary">
					<p>Students and faculty in Indianapolis benefit from close proximity to some of Indiana’s largest teaching hospitals and the Richard L. Roudebush Veterans Administration Medical Center. This campus offers medical education in the heart of one of the most progressive and economically healthy cities in the United States.</p>
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="campus-life"><a rel="page" href="/education/campuses/indianapolis/campus-life/">Campus Life</a></li>
							<li data-label="md-program"><a rel="page" href="/education/campuses/indianapolis/md-program/">MD Program</a></li>
							<li data-label="graduate-programs"><a rel="page" href="/education/graduate-degrees/">Graduate Programs</a></li>
							<li data-label="student-support"><a rel="page" href="/education/campuses/indianapolis/student-support/">Student Services</a></li>
							<li data-label="service-learning"><a rel="page" href="/education/campuses/indianapolis/service-learning/">Service Learning</a></li>
							<li data-label="research"><a rel="page" href="/education/campuses/indianapolis/research/">Research</a></li>
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="faculty"><a rel="page" href="/education/campuses/indianapolis/faculty/">Faculty</a></li>
							<li data-label="clinical-partners"><a rel="page" href="/education/campuses/indianapolis/clinical-partners/">Clinical Partners</a></li>
							<li data-label="news-events"><a rel="page" href="/education/campuses/indianapolis/news-events/">News and Events</a></li>
							<li data-label="contacts"><a rel="page" href="/education/campuses/indianapolis/contacts/">Contacts</a></li>
						</ul>
					</div>
				</div>
			</div>

			<div class="campus-detail" data-label="muncie">
				<span class="menu-header">Muncie</span>
				<div class="summary">
					<p>Muncie is the School’s only campus that’s located on hospital property, giving medical students a front-row four-year medical education with all the amenities that come with being located near the campus of Ball State University, a bustling college environment.</p>
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="campus-life"><a rel="page" href="/education/campuses/muncie/campus-life/">Campus Life</a></li>
							<li data-label="md-program"><a rel="page" href="/education/campuses/muncie/md-program/">MD Program</a></li>
							<li data-label="student-support"><a rel="page" href="/education/campuses/muncie/student-support/">Student Support</a></li>
							<li data-label="service-learning"><a rel="page" href="/education/campuses/muncie/service-learning/">Service Learning</a></li>
							<li data-label="research"><a rel="page" href="/education/campuses/muncie/research/">Research</a></li>
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="faculty"><a rel="page" href="/education/campuses/muncie/faculty/">Faculty</a></li>
							<li data-label="giving"><a rel="page" href="/education/campuses/muncie/giving/">Giving</a></li>
							<li data-label="clinical-partners"><a rel="page" href="/education/campuses/muncie/clinical-partners/">Clinical Partners</a></li>
							<li data-label="news-events"><a rel="page" href="/education/campuses/muncie/news-events/">News and Events</a></li>
							<li data-label="contacts"><a rel="page" href="/education/campuses/muncie/contacts/">Contacts</a></li>
						</ul>
					</div>
				</div>
			</div>

			<div class="campus-detail" data-label="gary">
				<span class="menu-header">Northwest – Gary</span>
				<div class="summary">
					<p>Located in a highly populated urban region just 25 miles from downtown Chicago, the Gary campus offers medical students unparalleled access to clinical care at 11 major teaching hospitals housing 2800 beds. An expanded residency program in Gary will accommodate more than 100 new graduate medical education positions.</p>
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="campus-life"><a rel="page" href="/education/campuses/gary/campus-life/">Campus Life</a></li>
							<li data-label="md-program"><a rel="page" href="/education/campuses/gary/md-program/">MD Program</a></li>
							<li data-label="student-support"><a rel="page" href="/education/campuses/gary/student-support/">Student Support</a></li>
							<li data-label="services-learning"><a rel="page" href="/education/campuses/gary/service-learning/">Service Learning</a></li>
							<li data-label="research"><a rel="page" href="/education/campuses/gary/research/">Research</a></li>
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="faculty"><a rel="page" href="/education/campuses/gary/faculty/">Faculty</a></li>
							<li data-label="giving"><a rel="page" href="/education/campuses/gary/giving/">Giving</a></li>
							<li data-label="clinical-partners"><a rel="page" href="/education/campuses/gary/clinical-partners/">Clinical Partners</a></li>
							<li data-label="news-events"><a rel="page" href="/education/campuses/gary/news-events/">News and Events</a></li>
							<li data-label="contacts"><a rel="page" href="/education/campuses/gary/contacts/">Contacts</a></li>
						</ul>
					</div>
				</div>
			</div>

			<div class="campus-detail" data-label="south-bend">
				<span class="menu-header">South Bend</span>
				<div class="summary">
					<p>IU School of Medicine-South Bend is located on the campus of Notre Dame, offering a rich campus life in a traditionally collegiate community. Students here gain clinical care experience at the Navari Student Outreach Clinic, and external funding for faculty research exceeds $2 million per year.</p>
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="campus-life"><a rel="page" href="/education/campuses/south-bend/campus-life/">Campus Life</a></li>
							<li data-label="md-program"><a rel="page" href="/education/campuses/south-bend/md-program/">MD Program</a></li>
							<li data-label="student-support"><a rel="page" href="/education/campuses/south-bend/student-support/">Student Services</a></li>
							<li data-label="service-learning"><a rel="page" href="/education/campuses/south-bend/service-learning/">Service Learning</a></li>
							<li data-label="research"><a rel="page" href="/education/campuses/south-bend/research/">Research</a></li>
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="faculty"><a rel="page" href="/education/campuses/south-bend/faculty/">Faculty</a></li>
							<li data-label="giving"><a rel="page" href="/education/campuses/south-bend/giving/">Giving</a></li>
							<li data-label="clinical-partners"><a rel="page" href="/education/campuses/south-bend/clinical-partners/">Clinical Partners</a></li>
							<li data-label="news-events"><a rel="page" href="/education/campuses/south-bend/news-events/">News and Events</a></li>
							<li data-label="contacts"><a rel="page" href="/education/campuses/south-bend/contacts/">Contacts</a></li>
						</ul>
					</div>
				</div>
			</div>

			<div class="campus-detail" data-label="terre-haute">
				<span class="menu-header">Terre Haute</span>
				<div class="summary">
					<p>Known for its rural medical education program, IU School of Medicine-Terre Haute meets the increased need for physicians to serve rural communities throughout the state of Indiana and beyond. This unique four-year medical school program emphasizes primary care and other specialties of need in rural communities.</p>
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="campus-life"><a rel="page" href="/education/campuses/terre-haute/campus-life/">Campus Life</a></li>
							<li data-label="md-program"><a rel="page" href="/education/campuses/terre-haute/md-program/">MD Program</a></li>
							<li data-label="student-support"><a rel="page" href="/education/campuses/terre-haute/student-support/">Student Services</a></li>
							<li data-label="service-learning"><a rel="page" href="/education/campuses/terre-haute/service-learning/">Service Learning</a></li>
							<li data-label="research"><a rel="page" href="/education/campuses/terre-haute/research/">Research</a></li>
						</ul>

					</div>
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="faculty"><a rel="page" href="/education/campuses/terre-haute/faculty/">Faculty</a></li>
							<li data-label="giving"><a rel="page" href="/education/campuses/terre-haute/giving/">Giving</a></li>
							<li data-label="clinical-partners"><a rel="page" href="/education/campuses/terre-haute/clinical-partners/">Clinical Partners</a></li>
							<li data-label="news-events"><a rel="page" href="/education/campuses/terre-haute/news-events/">News and Events</a></li>
							<li data-label="contacts"><a rel="page" href="/education/campuses/terre-haute/contacts/">Contacts</a></li>
						</ul>
					</div>
				</div>
			</div>

			<div class="campus-detail" data-label="west-lafayette">
				<span class="menu-header">West Lafayette</span>
				<div class="summary">
					<p>Located on the campus of Purdue University, the West Lafayette campus offers a Big Ten campus atmosphere and opportunities to supplement the MD curriculum with research experience in the collaborative labs and research centers here. This IU School of Medicine campus offers on-campus housing to med students.</p>
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="campus-life"><a rel="page" href="/education/campuses/west-lafayette/campus-life/">Campus Life</a></li>
							<li data-label="md-program"><a rel="page" href="/education/campuses/west-lafayette/md-program/">MD Program</a></li>
							<li data-label="student-support"><a rel="page" href="/education/campuses/west-lafayette/student-support/">Student Services</a></li>
							<li data-label="service-learning"><a rel="page" href="/education/campuses/west-lafayette/service-learning/">Service Learning</a></li>
							<li data-label="research"><a rel="page" href="/education/campuses/west-lafayette/research/">Research</a></li>
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="faculty"><a rel="page" href="/education/campuses/west-lafayette/faculty/">Faculty</a></li>
							<li data-label="giving"><a rel="page" href="/education/campuses/west-lafayette/giving/">Giving</a></li>
							<li data-label="clinical-partners"><a rel="page" href="/education/campuses/west-lafayette/clinical-partners/">Clinical Partners</a></li>
							<li data-label="news-events"><a rel="page" href="/education/campuses/west-lafayette/news-events/">News and Events</a></li>
							<li data-label="contacts"><a rel="page" href="/education/campuses/west-lafayette/contacts/">Contacts</a></li>
						</ul>
					</div>
				</div>

			</div>

			<div class="md-detail" data-label="md.student-support">
				<span class="menu-header">Student Support</span>
				<div class="summary">
					<p>IU School of Medicine provides a wide range of student support services to ensure that students can access the resources and guidance they need to succeed.</p>
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="md.student-support.financial-aid"><a rel="page" href="/education/md/student-support/financial-aid/">Financial Aid</a></li>
							<li data-label="md.student-support.mentoring.html"><a rel="12506" href="/education/md/student-support/mentoring-advising/">Mentoring and Advising</a></li>
							<li data-label="md.student-support.health-wellness"><a rel="page" href="/education/md/student-support/health-wellness/">Health and Wellness</a></li>
							<li data-label="md.student-support.tlac.html"><a target="_blank" rel="12511" href="http://mse.medicine.iu.edu/student-affairs/mentoring-advising/tlac.html">Teacher Learner Advocacy Committee</a></li>
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="md.student-support.disability-accomodations"><a rel="page" href="/education/md/student-support/disability-accomodations/">Disability Accommodations</a></li>			
						</ul>
					</div>
				</div>
			</div>

			<div class="md-detail active" data-label="md.admissions">
				<span class="menu-header">MD Admissions</span>
				<div class="summary">
					<p>Applicants to the IU School of Medicine MD Program, including guest students, can find details about application requirements and the admissions process, including interviews, class selection and campus placement.</p>
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
             <li data-label="md.admissions.admissions-overview"><a rel="page" href="/education/md/admissions/">MD Admissions Overview</a></li>
							<li data-label="md.admissions.application-materials"><a rel="page" href="/education/md/admissions/application-materials/">Supplemental Materials</a></li>
							<li data-label="md.admissions.interview"><a rel="page" href="/education/md/admissions/interview/">Interview Day</a></li>
							<li data-label="md.admissions.class-selection"><a rel="page" href="/education/md/admissions/class-selection/">Class Selection</a></li>
							
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="mm-menu">
              <li data-label="md.admissions.campus-placement"><a rel="page" href="/education/md/admissions/campus-placement/">Campus Placement</a></li>
							<li data-label="md.admissions.orientation"><a rel="page" href="/education/md/admissions/orientation/">Orientation</a></li>
							<li data-label="md.admissions.matriculation"><a rel="page" href="/education/md/admissions/matriculation/">Matriculation</a></li>
							<li data-label="md.admissions.guest-students"><a rel="page" href="/education/md/admissions/guest-students/">Guest Students</a></li>
						</ul>
					</div>
				</div>				
			</div>
			
			<div class="md-detail" data-label="md.curriculum">
				<span class="menu-header">Curriculum</span>
				<div class="summary">
					<p>The MD curriculum integrates clinical experiences and basic sciences and offers opportunities for learners to explore foundational science in a chosen specialty. Collaboration within learning communities and inter-professional work further enhance training.</p>
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="md.curriculum.competencies"><a href="/education/md/curriculum/competencies/">Competencies</a></li>
							<li data-label="md.curriculum.governance"><a href="/education/md/curriculum/governance/">Governance</a></li>
							<li data-label="md.curriculum.year-one-year-two"><a href="/education/md/curriculum/year-one-year-two/">Phase One</a></li>
							<li data-label="md.curriculum.year-three"><a href="/education/md/curriculum/year-three/">Phase Two</a></li>
							<li data-label="md.curriculum.year-four"><a href="/education/md/curriculum/year-four/">Phase Three</a></li>
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="md.curriculum.academic-calendar"><a href="/education/md/curriculum/academic-calendar/">Academic Calendar</a></li>
							<li data-label="md.curriculum.faq"><a href="/education/md/curriculum/faq/">FAQ</a></li>
							<li data-label="md.curriculum.planning-and-evaluation"><a href="/education/md/curriculum/planning-and-evaluation/">Planning and Evaluation</a></li>
              <li data-label="md.curriculum.scholarly-concentrations"><a href="/education/md/curriculum/scholarly-concentrations/">Scholarly Concentrations</a></li>
						</ul>
					</div>
				</div>				
			</div>
			
			<div class="md-detail" data-label="md.lcme-accreditation">
				<span class="menu-header">LCME Accreditation</span>
				<div class="summary">
					<p>In the United States, the accreditation status of programs leading to the MD degree is determined solely by the Liaison Committee on Medical Education (LCME). IU School of Medicine’s four-year MD program is LCME-accredited.</p>
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
							<!--<li data-label="md.lcme-accreditation.improvement-summaries"><a rel="page" href="/education/md/lcme-accreditation/improvement-summaries/">Improvement Summaries</a></li>-->
							<li data-label="md.lcme-accreditation.team"><a rel="page" href="/education/md/lcme-accreditation/team/">Accreditation Team</a></li>
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="mm-menu">
						</ul>
					</div>
				</div>
			</div>
			
			<div class="md-detail" data-label="md.dual-degrees">
				<span class="menu-header">Dual Degrees</span>
				<div class="summary">
					<p>MD students can complete requirements for one of five dual degrees—PhD, MBA, JD, MPH or MA—to prepare for a career that supplements expertise in clinical patient care with a second specialty.</p>
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="md.dual-degrees.team"><a rel="page" href="/education/md/dual-degrees/md-phd/">MSTP</a></li>
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="mm-menu">
						</ul>
					</div>
				</div>
			</div>
      
     	<div class="md-detail" data-label="md.residency-placement">
				<span class="menu-header">Residency Placement</span>			
				<div class="row">
					<div class="col-md-12">
						<ul class="mm-menu">
							<li data-label="md.dual-degrees.team"><a rel="page" href="/education/md/residency-placement/match-day/">What is Match Day?</a></li>
						</ul>
					</div>			
				</div>
			</div>
			
			<div class="md-detail" data-label="md.tuition">
				<span class="menu-header">Tuition and Fees</span>
				<div class="summary">
					<p>Annual tuition for the MD program at IU School of Medicine varies by stage of the medical education journey. Find details on cost of attendance for Indiana residents as well as out-of-state students.</p>
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
							<!--<li data-label="md.tuition.team"><a rel="page" href="/education/md/lcme-accreditation/team/">Accreditation Team</a></li>-->
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="mm-menu">
						</ul>
					</div>
				</div>
			</div>
			
			<div class="md-detail" data-label="md.service-learning">
				<span class="menu-header">Service Learning</span>
				<div class="summary">
					<p>The medical service learning program at IU School of Medicine actively engage students, physicians, faculty and community members in a dynamic partnership that connects community-identified concerns with institutional learning objectives.</p>
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
							<!--<li data-label="md.service-learning.team"><a rel="page" href="/education/md/lcme-accreditation/team/">Accreditation Team</a></li>-->
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="mm-menu">
							<!--<li data-label="md.service-learning.team"><a rel="page" href="/education/md/lcme-accreditation/team/">Accreditation Team</a></li>-->
						</ul>
					</div>
				</div>
			</div>
			
			<div class="md-detail" data-label="md.technical-standards">
				<span class="menu-header">Technical Standards</span>
				<div class="summary">
					<p>All MD program applicants and students are expected to meet the following criteria in order to participate in medical education at IU School of Medicine and to practice medicine.</p>
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
							<!--<li data-label="md.technical-standards.team"><a rel="page" href="/education/md/lcme-accreditation/team/">Accreditation Team</a></li>-->
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="mm-menu">
							<!--<li data-label="md.technical-standards.team"><a rel="page" href="/education/md/lcme-accreditation/team/">Accreditation Team</a></li>-->
						</ul>
					</div>
				</div>
			</div>
			
			
			<div class="md-detail" data-label="medical-library.services">
				<span class="menu-header">Ruth Lilly Medical Library</span>
				<div class="summary">
					<p>he Ruth Lilly Medical Library provides the physicians, researchers and learners at IU School of Medicine with access to the world’s evolving scientific and biomedical literature.</p>
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="medical-library.services"><a rel="page" href="/education/medical-library/services/liaisons/">Library Liaisons</a></li>
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="mm-menu">
							<!--<li data-label="md.technical-standards.team"><a rel="page" href="/education/md/lcme-accreditation/team/">Accreditation Team</a></li>-->
						</ul>
					</div>
				</div>
			</div>

			<ul class="mm-menu" data-label="residency-programs">
				<li data-label="residency-programs.application-requirements"><a rel="page" href="/education/gme/residency-programs/application-requirements/">Application Requirements</a></li>
				<li data-label="residency-programs.transitional-year"><a rel="page" href="/education/gme/residency-programs/transitional-year/">Transitional Year Residency</a></li>
				<li data-label="residency-programs.global-health"><a rel="page" href="/education/gme/residency-programs/global-health/">Global Health</a></li>
			</ul>

			<ul class="mm-menu" data-label="employment-terms-benefits">
				<li data-label="employment-terms-benefits.technical-standards"><a rel="page" href="/education/gme/employment-terms-benefits/technical-standards/">Technical Standards</a></li>
				<li data-label="employment-terms-benefits.personal-counseling"><a rel="page" href="/education/gme/employment-terms-benefits/mental-health-services/">Mental Health Services</a></li>
				<li data-label="employment-terms-benefits.policies"><a rel="page" href="/education/gme/employment-terms-benefits/policies/">Policies</a></li>
				<li data-label="employment-terms-benefits.faq"><a rel="page" href="/education/gme/employment-terms-benefits/faq/">Employment FAQs</a></li>
				<li data-label="employment-terms-benefits.resources"><a rel="page" href="/education/gme/employment-terms-benefits/resources/">Resources</a></li>
			</ul>

			<ul class="mm-menu" data-label="enrollment-orientation">
				<li data-label="enrollment-orientation.faq"><a rel="page" href="/education/gme/enrollment-orientation/faq/">Orientation FAQ</a></li>
			</ul>

			<ul class="mm-menu" data-label="degrees">
				<li data-label="degrees.associate-paramedic-science"><a rel="page" href="/education/undergraduate-health-professions/degrees/associate-paramedic-science/">Paramedic Science</a></li>
				<li data-label="degrees.associate-histotechnology"><a rel="page" href="/education/undergraduate-health-professions/degrees/associate-histotechnology/">Histotechnology</a></li>
				<li data-label="degrees.associate-radiography"><a rel="page" href="/education/undergraduate-health-professions/degrees/associate-radiography/">Radiography</a></li>
				<li data-label="degrees.bachelor-clinical-laboratory-science"><a rel="page" href="/education/undergraduate-health-professions/degrees/bachelor-clinical-laboratory-science/">Clinical Laboratory Science</a></li>
				<li data-label="degrees.bachelor-cytotechnology"><a rel="page" href="/education/undergraduate-health-professions/degrees/bachelor-cytotechnology/">Cytotechnology</a></li>
				<li data-label="degrees.bachelor-medical-imaging-technology"><a rel="page" href="/education/undergraduate-health-professions/degrees/bachelor-medical-imaging-technology/">Medical Imaging Technology</a></li>
				<li data-label="degrees.bachelor-nuclear-medicine-technology"><a rel="page" href="/education/undergraduate-health-professions/degrees/bachelor-nuclear-medicine-technology/">Nuclear Medicine Technology</a></li>
				<li data-label="degrees.bachelor-radiation-therapy"><a rel="page" href="/education/undergraduate-health-professions/degrees/bachelor-radiation-therapy/">Radiation Therapy</a></li>
				<li data-label="degrees.bachelor-respiratory-therapy"><a rel="page" href="/education/undergraduate-health-professions/degrees/bachelor-respiratory-therapy/">Respiratory Therapy</a></li>
			</ul>

			<ul class="mm-menu" data-label="admissions">
				<li data-label="admissions.associate-histotechnology"><a rel="page" href="/education/undergraduate-health-professions/admissions/associate-histotechnology/">Histotechnology, AS</a></li>
				<li data-label="admissions.certificate-histotechnology"><a rel="page" href="/education/undergraduate-health-professions/admissions/certificate-histotechnology/">Histotechnology Certificate</a></li>
				<li data-label="technical-standards"><a rel="page" href="/education/undergraduate-health-professions/admissions/technical-standards/">Technical Standards</a></li>
			</ul>

            <ul class="mm-menu" data-label="phd-programs">
                <li data-label="phd-programs.admissions"><a rel="page" href="/education/graduate-degrees/phd/bloomington/">Bloomington</a></li>
                <li data-label="phd-programs.curriculum"><a rel="page" href="/education/graduate-degrees/phd/indianapolis/">Indianapolis</a></li>
            </ul>
			
			<ul class="mm-menu" data-label="maintenance-of-certification">
                <li data-label="maintenance-of-certification.FAQ"><a rel="page" href="/education/cme/maintenance-of-certification/faq/">FAQ</a></li>
            </ul>
			
			<ul class="mm-menu" data-label="faculty-presenters">
                <li data-label="faculty-presenters.FAQ"><a rel="page" href="/education/cme/faculty-presenters/faq/">FAQ</a></li>
            </ul>
			
			<ul class="mm-menu" data-label="plan">
                <li data-label="plan.accreditation"><a rel="page" href="/education/cme/plan/accreditation/">Accreditation</a></li>
				<li data-label="plan.policies"><a rel="page" href="/education/cme/plan/policies/">Policies</a></li>
				<li data-label="plan.pricing"><a rel="page" href="/education/cme/plan/pricing/">Pricing</a></li>
            </ul>
			
			<ul class="mm-menu" data-label="contacts">
                <li data-label="contacts.advisory-committee"><a rel="page" href="/education/cme/contacts/advisory-committee/">Advisory Committee</a></li>				
            </ul>
			
						
		</div>
	</div>
</div>


