<div class="megamenu-panel multi-tier" id="megamenu-give" data-target="give">
	<div class="bg row"></div>
	<div class="fg row">

		<div class="col-md-3 mm-tier tier-1">
			<ul class="mm-menu active">
				<li data-label="gift-types"><a rel="page" href="/give/gift-types/">Gift Types</a></li>
				<li data-label="alumni"><a rel="page" href="/give/alumni/">Alumni</a></li>
				<li data-label="donor-recognition"><a rel="page" href="/give/donor-recognition/">Donor Recognition</a></li>
				<li data-label="contacts"><a rel="page" href="/give/contacts/">Contacts</a></li>				
				
			</ul>
		</div>

    <div class="col-md-3 mm-tier tier-2">

      <ul class="mm-menu active" data-label="gift-types">
        <li data-label="memorial-gifts">
          <a rel="page" href="/give/gift-types/memorial/">Memorial Gifts</a>
        </li>
        <li data-label="endowment" class="active">
          <a rel="page" href="/give/gift-types/endowment/">Endowment</a>
        </li>
        <li data-label="planned-and-estate-gifts">
          <a rel="page" href="/give/gift-types/planned/">Planned and Estate Gifts</a>
        </li>
        <li data-label="corporate-giving">
          <a rel="page" href="/give/gift-types/corporate/">Corporate Giving</a>
        </li>
        <li data-label="foundation">
          <a rel="page" href="/give/gift-types/foundation/">Foundation</a>
        </li>
        <li data-label="fundraising">
          <a rel="page" href="/give/gift-types/fundraising/">Fundraising</a>
        </li>

        <li data-label="body-donation">
          <a rel="page" href="/give/gift-types/body-donation/">Body Donation</a>
        </li>

      </ul>

      <ul class="mm-menu" data-label="alumni">
        <li data-label="awards">
          <a rel="page" href="/give/alumni/awards/">Awards</a>
        </li>
        <li data-label="programs-for-medical-students">
          <a rel="page" href="/give/alumni/programs-for-medical-students/">Programs For Medical Students</a>
        </li>
        <li data-label="membership">
          <a rel="page" href="/give/alumni/membership/">Membership</a>
        </li>
        <li data-label="news-and-events">
          <a rel="page" href="/give/alumni/news-events/">Alumni Events</a>
        </li>
        <li data-label="contacts">
          <a rel="page" href="/give/alumni/contacts/">Contacts</a>
        </li>

      </ul>

      <ul class="mm-menu" data-label="donor-recognition">
        <li data-label="deans-council">
          <a rel="page" href="/give/donor-recognition/deans-council/">Deans Council</a>
        </li>
        <li data-label="ritchey-society">
          <a rel="page" href="/give/donor-recognition/j-o-ritchey-society/">J.O. Ritchey Society</a>
        </li>

      </ul>

      <ul class="mm-menu" data-label="contacts">
        <li data-label="phd-programs">
          <a rel="page" href="/give/contacts/elkas/">Elizabeth A. Elkas</a>
        </li>
        <li data-label="masters-degrees">
          <a rel="page" href="/give/contacts/conkle/">Lizzie Conkle</a>
        </li>
        <li data-label="certificates">
          <a rel="page" href="/give/contacts/kooiman/">Jill Kooiman</a>
        </li>
        <li data-label="lgrad-programs">
          <a rel="page" href="/give/contacts/maxell/">Mary Maxwell</a>
        </li>
        <li data-label="mstp">
          <a rel="page" href="/give/contacts/red/">Kathryn Red</a>
        </li>
        <li data-label="education-phd-track">
          <a rel="page" href="/give/contacts/robinson/">Stacy Robinson</a>
        </li>
        <li data-label="education-phd-track">
          <a rel="page" href="/give/contacts/senseny/">Amber Kleopfer Senseny</a>
        </li>
        <li data-label="education-phd-track">
          <a rel="page" href="/give/contacts/mcgraw/">Andrea Spahn-Mcgraw</a>
        </li>
        <li data-label="education-phd-track">
          <a rel="page" href="/give/contacts/stewart/">Caitie Deranek Stewart</a>
        </li>
        <li data-label="education-phd-track">
          <a rel="page" href="/give/contacts/ueber/">Tim Ueber</a>
        </li>

      </ul>


    </div>
		<div class="col-md-6 mm-tier tier-3">

			<div class="campus-detail" data-label="endowment">
				<span class="menu-header">Endowment</span>
				<div class="summary">
					
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="endowment.research"><a rel="page" href="/give/gift-types/endowment/research/">Research</a></li>
							<li data-label="endowment.medical-education"><a rel="page" href="/give/gift-types/endowment/medical-education/">Medical Education</a></li>
							<li data-label="endowment.faculty-development"><a rel="page" href="/give/gift-types/endowment/faculty-development/">Faculty Development</a></li>
						
						</ul>
					</div>					
				</div>
			</div>

			<div class="campus-detail" data-label="planned-and-estate-gifts">
				<span class="menu-header">Planned and Estate Gifts</span>
				<div class="summary">
					<p></p>
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="requests"><a rel="page" href="/give/gift-types/planned/bequests/">Bequests</a></li>
							<li data-label="retirement"><a rel="page" href="/give/gift-types/planned/retirement/">Retirement</a></li>
											
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="mm-menu">
              <li data-label="annuity">
                <a rel="page" href="/give/gift-types/planned/annuity/">Annuity</a>
              </li>
              <li data-label="real-estate">
                <a rel="page" href="/give/gift-types/planned/real-estate/">Real Estate</a>
              </li>
						</ul>
					</div>
				</div>
			</div>

			<div class="campus-detail" data-label="fundraising">
				<span class="menu-header">Fundraising</span>
				<div class="summary">
					<p></p>
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="bigelow-open"><a rel="page" href="/give/gift-types/fundraising/bigelow-open/">Bigelow Open</a></li>
						
						</ul>
					</div>
          <div class="col-md-6">
            <ul class="mm-menu">
              <li data-label="Diversity-recruitment">
                <a rel="page" href="/give/gift-types/fundraising/diversity-recruitment-scholarship/">Diversity Recruitment Scholarship</a>
              </li>
            </ul>
          </div>
				</div>
			</div>



      <div class="campus-detail" data-label="body-donation">
        <span class="menu-header">Body Donation</span>
        <div class="summary">
          <p></p>
        </div>
        <div class="row">
          <div class="col-md-6">
            <ul class="mm-menu">
              <li data-label="bigelow-open">
                <a rel="page" href="/give/gift-types/body-donation/bequeathal-form-request/">Bequeathal Form Request </a></li>
            </ul>
          </div>       
        </div>
      </div>










      <div class="md-detail" data-label="awards">
				<span class="menu-header">Awards</span>
				<div class="summary">
					<p></p>
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="distinguished-medical-alumni-award"><a rel="page" href="/give/alumni/awards/distinguished-medical-alumni/">Distinguished Medical Alumni Award</a></li>
							<li data-label="early-career-achievement"><a rel="12506" href="/give/alumni/awards/early-career-achievement/">Early Career Achievement</a></li>
							
														
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="mm-menu">
              <li data-label="distinguished-faculty"><a rel="page" href="/give/alumni/awards/distinguished-faculty/">Distinguished Faculty</a> </li>		
            </ul>
					</div>
				</div>
			</div>

			<div class="md-detail" data-label="programs-for-medical-students">
				<span class="menu-header">Programs For Medical Students</span>
				<div class="summary">
					<p></p>
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="help-students-travel"><a rel="page" href="/give/alumni/programs-for-medical-students/help-students-travel/">Help Students Travel</a></li>
							<li data-label="student-application-form"><a rel="page" href="/give/alumni/programs-for-medical-students/student-application-form/">Student Application Form</a></li>
					
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="mm-menu">
              <li data-label="alumni-application-form">
                <a rel="page" href="/give/alumni/programs-for-medical-students/alumni-application-form/">Alumni Application Form</a>
              </li>
						</ul>
					</div>
				</div>				
			</div>
			
			<div class="md-detail" data-label="news-and-events">
				<span class="menu-header">Events</span>
				<div class="summary">
					<p></p>
				</div>
				<div class="row">
					<div class="col-md-6">
						<ul class="mm-menu">
							<li data-label="alumni-weekend"><a href="/give/alumni/news-events/medical-alumni-weekend/">Alumni Weekend</a></li>
							
						</ul>
					</div>
					
				</div>				
			</div>	

		</div>
	</div>
</div>


