<div class="megamenu-panel multi-tier" id="megamenu-news" data-target="news">
  <div class="bg row"></div>
  <div class="fg row">

    <div class="col-md-3 mm-tier tier-1 mm-left">

      <ul class="mm-menu active">
        
        <li data-label="news-releases">
          <a rel="page" href="/news/all-news/">News Releases</a>
        </li>

        <li data-label="communication">
          <a rel="page" href="/communications/">Communications</a>
        </li>
        
        <li data-label="blogs">
          <a rel="page" href="/blogs/">Blogs</a>
        </li>

        <li data-label="events">
          <a rel="page" href="/events/">Events</a>
        </li>

     
      </ul>
    </div>


    <div class="col-md-9 mm-tier tier-2 mm-right">
    
      <div class="expertise-detail active" data-label="news-releases">
        <span class="menu-header">News Releases</span>
        <div class="summary">
          <p></p>
        </div>
        <div class="row">
          <div class="col-md-3">
            <ul class="mm-menu" data-label="news-releases">
              <li data-label="aging">
                <a rel="page" href="/news/tag/aging/">Aging</a>
              </li>
              <li data-label="alzheimer">
                <a rel="page" href="/news/tag/alzheimers-disease/">Alzheimer's Disease</a>
              </li>
              <li data-label="cancer">
                <a rel="page" href="/news/tag/cancer/">Cancer</a>
              </li>
     

            </ul>
          </div>
          <div class="col-md-3">
            <ul class="mm-menu" data-label="news-releases">
              <li data-label="diabetes">
                <a rel="page" href="/news/tag/diabetes/">Diabetes</a>
              </li>
              <li data-label="education-programs">
                <a rel="page" href="/news/tag/education-programs/">Education Programs</a>
              </li>
              <li data-label="global-health">
                <a rel="page" href="/news/tag/global-health/">Global Health</a>
              </li>
             
            </ul>
          </div>
          <div class="col-md-3">
            <ul class="mm-menu" data-label="news-releases">
              <li data-label="indiana-health">
                <a rel="page" href="/news/tag/indiana-health/">Indiana Health</a>
              </li>
              <li data-label="musuloskeletal">
                <a rel="page" href="/news/tag/musculoskeletal-health/">Musculoskeletal Health</a>
              </li>
              <li data-label="pediatrics">
                <a rel="page" href="/news/tag/pediatrics/">Pediatrics</a>
              </li>
            </ul>
          </div>
         <div class="col-md-3">
            <ul class="mm-menu" data-label="news-releases">
              <li data-label="personalized-medicine">
                <a rel="page" href="/news/tag/precision-health/">Precision Health</a>
              </li>
              <li data-label="research-findings">
                <a rel="page" href="/news/tag/research-findings/">Research Findings</a>
              </li>
           
            </ul>
          </div>
        </div>
      </div>
      
      
      <div class="expertise-detail" data-label="communication">
        <span class="menu-header">Communications</span>
        <div class="summary">
          <p></p>
        </div>
        <div class="row">
          <div class="col-md-6">
            <ul class="mm-menu" data-label="communication">
              <li data-label="media-relations">
                <a rel="page" href="/communication/media-relations/">Media Relations</a>
              </li>
              <li data-label="contacts">
                <a rel="page" href="/communications/contacts/">Contacts</a>
              </li>
              <li data-label="social">
                <a rel="page" href="/communication/social/">Social</a>
              </li>
              <li data-label="internal">
                <a rel="page" href="/communications/internal/">Internal</a>
              </li>




            </ul>
          </div>
          <div class="col-md-6">
            <ul class="mm-menu" data-label="communication">

              <li data-label="visual-media">
                <a rel="page" href="/communications/visual-media/">Visual Media </a>
              </li>
              <li data-label="branding">
                <a rel="page" href="/communication/branding/">Branding</a>
              </li>
              <li data-label="submit-news">
                <a rel="page" href="/communications/submit/">Submit News</a>
              </li>


            </ul>
          </div>

        </div>
      </div>


      <div class="expertise-detail" data-label="blogs">
        <span class="menu-header">Blogs</span>
        <div class="summary">
          <p></p>
        </div>
        <div class="row">
          <div class="col-md-4">
            <ul class="mm-menu" data-label="blogs">
              <li data-label="bloomington">
                <a rel="page" href="/blogs/alumni/">Alumni</a>
              </li>
              <li data-label="evansville">
                <a rel="page" href="/blogs/faculty-news/">Faculty News</a>
              </li>
              <li data-label="fort-wayne">
                <a rel="page" href="/blogs/global-health/">Global Health</a>
              </li>
     

            </ul>
          </div>
          <div class="col-md-4">
            <ul class="mm-menu" data-label="blogs">
              <li data-label="indianapolis">
                <a rel="page" href="/blogs/medical-library/">Medical Library</a>
              </li>
              <li data-label="muncie">
                <a rel="page" href="/blogs/pediatrics/">Pediatrics </a>
              </li>
              <li data-label="gary">
                <a rel="page" href="/blogs/research-updates/">Research Updates</a>
              </li>
             
            </ul>
          </div>
          <div class="col-md-4">
            <ul class="mm-menu" data-label="blogs">
              <li data-label="south-bend">
                <a rel="page" href="/blogs/spirit-of-medicine/">Spirit of Medicine</a>
              </li>
              <li data-label="terre-haute">
                <a rel="page" href="/blogs/strategic-voices/">Strategic Voices</a>
              </li>
              <li data-label="west-lafayette">
                <a rel="page" href="/blogs/women-in-medicine/">Women in Medicine</a>
              </li>
            </ul>
          </div>
        </div>
      </div>


      <div class="expertise-detail" data-label="events">
        <span class="menu-header">Events</span>
        <div class="summary">
          <p></p>
        </div>
        <div class="row">
          <div class="col-md-4">
            <ul class="mm-menu" data-label="events">
              <li data-label="bloomington">
                <a rel="page" href="/campuses/bloomington/news-events/">Bloomington</a>
              </li>
              <li data-label="evansville">
                <a rel="page" href="/campuses/evansville/news-events/">Evansville</a>
              </li>
              <li data-label="fort-wayne">
                <a rel="page" href="/campuses/fort-wayne/news-events/">Fort Wayne</a>
              </li>


            </ul>
          </div>
          <div class="col-md-4">
            <ul class="mm-menu" data-label="events">
              <li data-label="indianapolis">
                <a rel="page" href="/campuses/indianapolis/news-events/">Indianapolis</a>
              </li>
              <li data-label="muncie">
                <a rel="page" href="/campuses/muncie/news-events/">Muncie </a>
              </li>
              <li data-label="gary">
                <a rel="page" href="/campuses/gary/news-events/">Gary</a>
              </li>

            </ul>
          </div>
          <div class="col-md-4">
            <ul class="mm-menu" data-label="events">
              <li data-label="south-bend">
                <a rel="page" href="/campuses/south-bend/news-events/">South Bend</a>
              </li>
              <li data-label="terre-haute">
                <a rel="page" href="/campuses/terre-haute/news-events/">Terre Haute</a>
              </li>
              <li data-label="west-lafayette">
                <a rel="page" href="/campuses/west-lafayette/news-events/">West Lafayette</a>
              </li>
            </ul>
          </div>
        </div>
      </div>




    
    

      


    </div>


  </div>
</div>


