<div class="megamenu-panel multi-tier" id="megamenu-campus" data-target="campuses">
    <div class="bg row"></div>
    <div class="fg row">

        <div class="col-md-3 mm-tier tier-1 mm-left">
            <ul class="mm-menu active">
                <li data-label="bloomington"><a rel="page" href="/campuses/bloomington/">Bloomington</a></li>
                <li data-label="evansville"><a rel="page" href="/campuses/evansville/">Evansville</a></li>
                <li data-label="fort-wayne"><a rel="page" href="/campuses/fort-wayne/">Fort Wayne</a></li>
                <li data-label="indianapolis"><a rel="page" href="/campuses/indianapolis/">Indianapolis</a></li>
                <li data-label="muncie"><a rel="page" href="/campuses/muncie/">Muncie</a></li>
                <li data-label="gary"><a rel="page" href="/campuses/gary/">Northwest – Gary</a></li>
                <li data-label="south-bend"><a rel="page" href="/campuses/south-bend/">South Bend</a></li>
                <li data-label="terre-haute"><a rel="page" href="/campuses/terre-haute/">Terre Haute</a></li>
                <li data-label="west-lafayette"><a rel="page" href="/campuses/west-lafayette/">West Lafayette</a></li>
            </ul>
        </div>

        <div class="col-md-9 mm-tier tier-2 mm-right">

            <div class="campus-detail active" data-label="bloomington">
                <span class="menu-header">Bloomington</span>
                <div class="summary">
                    <p>The Medical Sciences Program in Bloomington is unique among the IU School of Medicine campuses in that it educates medical students seeking an MD as well as graduate and undergraduate students. Bloomington offers a Big 10 learning environment on an iconic campus.</p>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <ul class="mm-menu">
                            <li data-label="bloomington.campus-life"><a rel="page" href="/campuses/bloomington/campus-life/">Campus Life</a></li>
                            <li data-label="bloomington.md-program"><a rel="page" href="/campuses/bloomington/md-program/">MD Program</a></li>
                            <li data-label="bloomington.graduate-programs"><a rel="page" href="/campuses/bloomington/graduate-programs/">Graduate Programs</a></li>
                            <li data-label="bloomington.undergraduate-programs"><a rel="page" href="/campuses/bloomington/undergraduate-programs/">Undergraduate Programs</a></li>
                            <li data-label="bloomington.student-support"><a rel="page" href="/campuses/bloomington/student-support/">Student Support</a></li>
                            <li data-label="bloomington.service-learning"><a rel="page" href="/campuses/bloomington/service-learning/">Service Learning</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <ul class="mm-menu">
                            <li data-label="bloomington.research"><a rel="page" href="/campuses/bloomington/research/">Research</a></li>
                            <li data-label="bloomington.faculty"><a rel="page" href="/campuses/bloomington/faculty/">Faculty</a></li>
                            <li data-label="bloomington.giving"><a rel="page" href="/campuses/bloomington/giving/">Giving</a></li>
                            <li data-label="bloomington.clinical-partners"><a rel="page" href="/campuses/bloomington/clinical-partners/">Clinical Partners</a></li>
                            <li data-label="bloomington.news-events"><a rel="page" href="/campuses/bloomington/news-events/">News and Events</a></li>
                            <li data-label="bloomington.contacts"><a rel="page" href="/campuses/bloomington/contacts/">Contacts</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="campus-detail" data-label="evansville">
                <span class="menu-header">Evansville</span>
                <div class="summary">
                    <p>With six major hospitals housing about 2000 beds, medical students in Evansville have access to physician educators in a range of medical specialties. An expanded residency program here will provide more than 100 new graduate medical education positions over the next few years.</p>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <ul class="mm-menu">
                            <li data-label="evansville.campus-life"><a rel="page" href="/campuses/evansville/campus-life/">Campus Life</a></li>
                            <li data-label="evansville.md-program"><a rel="page" href="/campuses/evansville/md-program/">MD Program</a></li>
                            <li data-label="evansville.student-support"><a rel="page" href="/campuses/evansville/student-support/">Student Support</a></li>
                            <li data-label="evansville.service-learning"><a rel="page" href="/campuses/evansville/service-learning/">Service Learning</a></li>
                            <li data-label="evansville.research"><a rel="page" href="/campuses/evansville/research/">Research</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <ul class="mm-menu">
                            <li data-label="evansville.faculty"><a rel="page" href="/campuses/evansville/faculty/">Faculty</a></li>
                            <li data-label="evansville.giving"><a rel="page" href="/campuses/evansville/giving/">Giving</a></li>
                            <li data-label="evansville.clinical-partners"><a rel="page" href="/campuses/evansville/clinical-partners/">Clinical Partners</a></li>
                            <li data-label="evansville.news-events"><a rel="page" href="/campuses/evansville/news-events/">News and Events</a></li>
                            <li data-label="evansville.contacts"><a rel="page" href="/campuses/evansville/contacts/">Contacts</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="campus-detail" data-label="fort-wayne">
                <span class="menu-header">Fort Wayne</span>
                <div class="summary">
                    <p>The Fort Wayne campus offers clinical education in both rural and urban communities through two large hospital systems serving the region. A Student Research Fellowship Program offers med students nine weeks of summer research experience.</p>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <ul class="mm-menu">
                            <li data-label="fort-wayne.campus-life"><a rel="page" href="/campuses/fort-wayne/campus-life/">Campus Life</a></li>
                            <li data-label="fort-wayne.md-program"><a rel="page" href="/campuses/fort-wayne/md-program/">MD Program</a></li>
                            <li data-label="fort-wayne.student-support"><a rel="page" href="/campuses/fort-wayne/student-support/">Student Support</a></li>
                            <li data-label="fort-wayne.service-learning"><a rel="page" href="/campuses/fort-wayne/service-learning/">Service Learning</a></li>
                            <li data-label="fort-wayne.research"><a rel="page" href="/campuses/fort-wayne/research/">Research</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <ul class="mm-menu">
                            <li data-label="fort-wayne.faculty"><a rel="page" href="/campuses/fort-wayne/faculty/">Faculty</a></li>
                            <li data-label="fort-wayne.giving"><a rel="page" href="/campuses/fort-wayne/giving/">Giving</a></li>
                            <li data-label="fort-wayne.clinical-partners"><a rel="page" href="/campuses/fort-wayne/clinical-partners/">Clinical Partners</a></li>
                            <li data-label="fort-wayne.news-events"><a rel="page" href="/campuses/fort-wayne/news-events/">News and Events</a></li>
                            <li data-label="fort-wayne.contacts"><a rel="page" href="/campuses/fort-wayne/contacts/">Contacts</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="campus-detail" data-label="indianapolis">
                <span class="menu-header">Indianapolis</span>
                <div class="summary">
                    <p>Students and faculty in Indianapolis benefit from close proximity to some of Indiana’s largest teaching hospitals and the Richard L. Roudebush Veterans Administration Medical Center. This campus offers medical education in the heart of one of the most progressive and economically healthy cities in the United States.</p>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <ul class="mm-menu">
                            <li data-label="indianapolis.campus-life"><a rel="page" href="/campuses/indianapolis/campus-life/">Campus Life</a></li>
                            <li data-label="indianapolis.md-program"><a rel="page" href="/campuses/indianapolis/md-program/">MD Program</a></li>
                            <li data-label="indianapolis.student-support"><a rel="page" href="/campuses/indianapolis/student-support/">Student Support</a></li>
                            <li data-label="indianapolis.service-learning"><a rel="page" href="/campuses/indianapolis/service-learning/">Service Learning</a></li>
                            <li data-label="indianapolis.research"><a rel="page" href="/campuses/indianapolis/research/">Research</a></li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <ul class="mm-menu">
                            <li data-label="indianapolis.faculty"><a rel="page" href="/campuses/indianapolis/faculty/">Faculty</a></li>
                            <li data-label="indianapolis.clinical-partners"><a rel="page" href="/campuses/indianapolis/clinical-partners/">Clinical Partners</a></li>
                            <li data-label="indianapolis.news-events"><a rel="page" href="/campuses/indianapolis/news-events/">News and Events</a></li>
                            <li data-label="indianapolis.contacts"><a rel="page" href="/campuses/indianapolis/contacts/">Contacts</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="campus-detail" data-label="muncie">
                <span class="menu-header">Muncie</span>
                <div class="summary">
                    <p>Muncie is the School’s only campus that’s located on hospital property, giving medical students a front-row four-year medical education with all the amenities that come with being located near the campus of Ball State University, a bustling college environment.</p>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <ul class="mm-menu">
                            <li data-label="muncie.campus-life"><a rel="page" href="/campuses/muncie/campus-life/">Campus Life</a></li>
                            <li data-label="muncie.md-program"><a rel="page" href="/campuses/muncie/md-program/">MD Program</a></li>
                            <li data-label="muncie.student-support"><a rel="page" href="/campuses/muncie/student-support/">Student Support</a></li>
                            <li data-label="muncie.service-learning"><a rel="page" href="/campuses/muncie/service-learning/">Service Learning</a></li>
                            <li data-label="muncie.research"><a rel="page" href="/campuses/muncie/research/">Research</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <ul class="mm-menu">
                            <li data-label="muncie.faculty"><a rel="page" href="/campuses/muncie/faculty/">Faculty</a></li>
                            <li data-label="muncie.giving"><a rel="page" href="/campuses/muncie/giving/">Giving</a></li>
                            <li data-label="muncie.clinical-partners"><a rel="page" href="/campuses/muncie/clinical-partners/">Clinical Partners</a></li>
                            <li data-label="muncie.news-events"><a rel="page" href="/campuses/muncie/news-events/">News and Events</a></li>
                            <li data-label="muncie.contacts"><a rel="page" href="/campuses/muncie/contacts/">Contacts</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="campus-detail" data-label="gary">
                <span class="menu-header">Nortwest - Gary</span>
                <div class="summary">
                    <p>Located in a highly populated urban region just 25 miles from downtown Chicago, the Gary campus offers medical students unparalleled access to clinical care at 11 major teaching hospitals housing 2800 beds. An expanded residency program in Gary will accommodate more than 100 new graduate medical education positions.</p>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <ul class="mm-menu">
                            <li data-label="gary.campus-life"><a rel="page" href="/campuses/gary/campus-life/">Campus Life</a></li>
                            <li data-label="gary.md-program"><a rel="page" href="/campuses/gary/md-program/">MD Program</a></li>
                            <li data-label="gary.student-support"><a rel="page" href="/campuses/gary/student-support/">Student Support</a></li>
                            <li data-label="gary.service-learning"><a rel="page" href="/campuses/gary/service-learning/">Service Learning</a></li>
                            <li data-label="gary.research"><a rel="page" href="/campuses/gary/research/">Research</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <ul class="mm-menu">
                            <li data-label="gary.faculty"><a rel="page" href="/campuses/gary/faculty/">Faculty</a></li>
                            <li data-label="gary.giving"><a rel="page" href="/campuses/gary/giving/">Giving</a></li>
                            <li data-label="gary.clinical-partners"><a rel="page" href="/campuses/gary/clinical-partners/">Clinical Partners</a></li>
                            <li data-label="gary.news-events"><a rel="page" href="/campuses/gary/news-events/">News and Events</a></li>
                            <li data-label="gary.contacts"><a rel="page" href="/campuses/gary/contacts/">Contacts</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="campus-detail" data-label="south-bend">
                <span class="menu-header">South Bend</span>
                <div class="summary">
                    <p>IU School of Medicine-South Bend is located on the campus of Notre Dame, offering a rich campus life in a traditionally collegiate community. Students here gain clinical care experience at the Navari Student Outreach Clinic, and external funding for faculty research exceeds $2 million per year.</p>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <ul class="mm-menu">
                            <li data-label="south-bend.campus-life"><a rel="page" href="/campuses/south-bend/campus-life/">Campus Life</a></li>
                            <li data-label="south-bend.md-program"><a rel="page" href="/campuses/south-bend/md-program/">MD Program</a></li>
                            <li data-label="south-bend.student-support"><a rel="page" href="/campuses/south-bend/student-support/">Student Support</a></li>
                            <li data-label="south-bend.service-learning"><a rel="page" href="/campuses/south-bend/service-learning/">Service Learning</a></li>
                            <li data-label="south-bend.research"><a rel="page" href="/campuses/south-bend/research/">Research</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <ul class="mm-menu">
                            <li data-label="south-bend.faculty"><a rel="page" href="/campuses/south-bend/faculty/">Faculty</a></li>
                            <li data-label="south-bend.giving"><a rel="page" href="/campuses/south-bend/giving/">Giving</a></li>
                            <li data-label="south-bend.clinical-partners"><a rel="page" href="/campuses/south-bend/clinical-partners/">Clinical Partners</a></li>
                            <li data-label="south-bend.news-events"><a rel="page" href="/campuses/south-bend/news-events/">News and Events</a></li>
                            <li data-label="south-bend.contacts"><a rel="page" href="/campuses/south-bend/contacts/">Contacts</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="campus-detail" data-label="terre-haute">
                <span class="menu-header">Terre Haute</span>
                <div class="summary">
                    <p>Known for its rural medical education program, IU School of Medicine-Terre Haute meets the increased need for physicians to serve rural communities throughout the state of Indiana and beyond. This unique four-year medical school program emphasizes primary care and other specialties of need in rural communities.</p>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <ul class="mm-menu">
                            <li data-label="terre-haute.campus-life"><a rel="page" href="/campuses/terre-haute/campus-life/">Campus Life</a></li>
                            <li data-label="terre-haute.md-program"><a rel="page" href="/campuses/terre-haute/md-program/">MD Program</a></li>
                            <li data-label="terre-haute.student-support"><a rel="page" href="/campuses/terre-haute/student-support/">Student Support</a></li>
                            <li data-label="terre-haute.service-learning"><a rel="page" href="/campuses/terre-haute/service-learning/">Service Learning</a></li>
                            <li data-label="terre-haute.research"><a rel="page" href="/campuses/terre-haute/research/">Research</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <ul class="mm-menu">
                            <li data-label="terre-haute.faculty"><a rel="page" href="/campuses/terre-haute/faculty/">Faculty</a></li>
                            <li data-label="terre-haute.giving"><a rel="page" href="/campuses/terre-haute/giving/">Giving</a></li>
                            <li data-label="terre-haute.clinical-partners"><a rel="page" href="/campuses/terre-haute/clinical-partners/">Clinical Partners</a></li>
                            <li data-label="terre-haute.news-events"><a rel="page" href="/campuses/terre-haute/news-events/">News and Events</a></li>
                            <li data-label="terre-haute.contacts"><a rel="page" href="/campuses/terre-haute/contacts/">Contacts</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="campus-detail" data-label="west-lafayette">
                <span class="menu-header">West Lafayette</span>
                <div class="summary">
                    <p>Located on the campus of Purdue University, the West Lafayette campus offers a Big Ten campus atmosphere and opportunities to supplement the MD curriculum with research experience in the collaborative labs and research centers here. This IU School of Medicine campus offers on-campus housing to med students.</p>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <ul class="mm-menu">
                            <li data-label="west-lafayette.campus-life"><a rel="page" href="/campuses/west-lafayette/campus-life/">Campus Life</a></li>
                            <li data-label="west-lafayette.md-program"><a rel="page" href="/campuses/west-lafayette/md-program/">MD Program</a></li>
                            <li data-label="west-lafayette.student-support"><a rel="page" href="/campuses/west-lafayette/student-support/">Student Support</a></li>
                            <li data-label="west-lafayette.service-learning"><a rel="page" href="/campuses/west-lafayette/service-learning/">Service Learning</a></li>
                            <li data-label="west-lafayette.research"><a rel="page" href="/campuses/west-lafayette/research/">Research</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <ul class="mm-menu">
                            <li data-label="west-lafayette.faculty"><a rel="page" href="/campuses/west-lafayette/faculty/">Faculty</a></li>
                            <li data-label="west-lafayette.giving"><a rel="page" href="/campuses/west-lafayette/giving/">Giving</a></li>
                            <li data-label="west-lafayette.clinical-partners"><a rel="page" href="/campuses/west-lafayette/clinical-partners/">Clinical Partners</a></li>
                            <li data-label="west-lafayette.news-events"><a rel="page" href="/campuses/west-lafayette/news-events/">News and Events</a></li>
                            <li data-label="west-lafayette.contacts"><a rel="page" href="/campuses/west-lafayette/contacts/">Contacts</a></li>
                        </ul>
                    </div>
                </div>
            </div>


        </div>


    </div>
</div>


