<div class="megamenu-panel multi-tier" id="megamenu-expertise" data-target="expertise">
  <div class="bg row"></div>
  <div class="fg row">

    <div class="col-md-3 mm-tier tier-1 mm-left">
      
      <ul class="mm-menu active">
        <li data-label="alzheimers">
          <a rel="page" href="/expertise/alzheimers/">Alzheimer's Disease</a>
        </li>

		<li data-label="indiana-health">
          <a rel="page" href="/expertise/indiana-health/">Indiana Health</a>
        </li>

        <li data-label="precision-health">
          <a rel="page" href="/expertise/precision-health-initiative/">Precision Health Initiative</a>
        </li>
        
        <li data-label="musculoskeletal-health">
          <a rel="page" href="/expertise/musculoskeletal-health/">Musculoskeletal Health</a>
        </li>
    
        <li data-label="traumatic-brain">
          <a rel="page" href="/expertise/traumatic-brain-injury/">Traumatic Brain Injury</a>
        </li>
        <li data-label="global-health">
          <a rel="page" href="/expertise/global-health/">Global Health</a>
        </li>
       
      </ul>
    </div>


     <div class="col-md-9 mm-tier tier-2 mm-right">
      <div class="expertise-detail active" data-label="alzheimers">
         <span class="menu-header">Alzheimer’s Disease</span>
           <div class="summary">
            <p>To better understand and end the suffering related to Alzheimer’s disease, IU School of Medicine’s accomplished team of experts are pioneering global collaboration of multidisciplinary dementia research to study the fundamental causes and treatment options.</p>
           </div>
          <div class="row">
            <div class="col-md-6">
              <ul class="mm-menu active" data-label="alzheimers">
                <li data-label="alzheimers">
                  <a rel="page" href="/expertise/alzheimers/what-is-alzheimers/">What is Alzheimers</a>
                </li>

                <li data-label="research">
                  <a rel="page" href="/expertise/alzheimers/research/">Research</a>
                </li>

                <li data-label="collaboration">
                  <a rel="page" href="/expertise/alzheimers/collaboration/">Collaboration</a>
                </li>
                </ul>
              </div>
            <div class="col-md-6">
              <ul class="mm-menu">
                <li data-label="clinical-trials">
                  <a rel="page" href="/expertise/alzheimers/clinical-trials/">Clinical Trials</a>
                </li>      
              </ul>
           </div>
         </div>
      </div>
        
  <div class="expertise-detail" data-label="indiana-health">
        <span class="menu-header">Indiana Health</span>
            <div class="summary">
              <p></p>
            </div>
     <div class="row">
        <div class="col-md-12">
      <ul class="mm-menu" data-label="indiana-health">
        <div class="col-md-6">
          <ul class="mm-menu">
             <li data-label="cancer">
          <a rel="page" href="/expertise/indiana-health/cancer/">Cancer</a>
         </li>   
        
          <li data-label="infant-mortality">
          <a rel="page" href="/expertise/indiana-health/infant-mortality/">Infant Mortality</a>
         </li>

            <li data-label="access-to-care">
              <a rel="page" href="/expertise/indiana-health/access-to-care/">Access to Care</a>
            </li>
           
          </ul>
        </div>
        <div class="col-md-6">
          <ul class="mm-menu">
            
            <li data-label="opioid-abuse">
              <a rel="page" href="/expertise/indiana-health/opioid-abuse/">Opioids Abuse Crisis</a>
            </li>


            <li data-label="mental-health">
              <a rel="page" href="/expertise/indiana-health/mental-health/">Mental Health</a>
            </li>


          </ul>
        
        </div>
             
         
        
       
      </ul>
      </div>
     </div>
    </div>  
    
        
  <div class="expertise-detail" data-label="precision-health">
        <span class="menu-header">Precision Health</span>
            <div class="summary">
              <p>Through the Precision Health Initiative, IU School of Medicine intends to cure at least one cancer through the development of new cell, gene and immune therapies and to develop novel disease-modifying or -prevention methods for adult neurodegenerative diseases such as Alzheimer’s Disease. The program is also using gene and other therapies to cure at least one genetic pediatric disease.</p>
            </div>
     <div class="row">
       <div class="col-md-6">
         <ul class="mm-menu" data-label="precision-health">
           <li data-label="what-is-precision-medicine">
             <a rel="page" href="/expertise/precision-health-initiative/what-is-precision-medicine/">What is Precision Medicine?</a>
           </li>
           <li data-label="research-outcomes">
             <a rel="page" href="/expertise/precision-health-initiative/research-outcomes/">Research Outcomes</a>
           </li>
           <li data-label="research-outcomes">
             <a rel="page" href="/expertise/precision-health-initiative/multiple-myeloma/">Multiple Myeloma</a>
           </li>
         </ul>
       </div>
       <div class="col-md-6">
          <ul class="mm-menu" data-label="precision-health">
            <li data-label="what-is-precision-medicine">
              <a rel="page" href="/expertise/precision-health-initiative/triple-negative-breast-cancer/">Triple Negative Breast Cancer</a></li>
            <li data-label="research-outcomes">
              <a rel="page" href="/expertise/precision-health-initiative/childhood-sarcoma/">Childhood Sarcoma</a></li>
            <li data-label="research-outcomes">
              <a rel="page" href="/expertise/precision-health-initiative/type-2-diabetes/">Type 2 Diabetes </a></li>
            <li data-label="research-outcomes">
            <a rel="page" href="/expertise/precision-health-initiative/alzheimers-disease/">Alzheimer’s Disease</a></li>
          </ul>
      </div>
     </div>
    </div>
       
  <div class="expertise-detail" data-label="musculoskeletal-health">
     <span class="menu-header">Musculoskeletal Health</span>
         <div class="summary">
              <p>IU School of Medicine researchers, educators and clinicians are collaborating to better understand and treat a broad range of diseases and disorders of the musculoskeletal system — bones, muscles, and joints.</p>
          </div>
     <div class="row">
       <div class="col-md-6">
      <ul class="mm-menu" data-label="musculoskeletal-health">
        <li data-label="what-is-musculoskeletal-health">
          <a rel="page" href="/expertise/musculoskeletal-health/what-is-musculoskeletal-health/">What is musculoskeletal health?</a>
        </li>
        <li data-label="mus.research">
          <a rel="page" href="/expertise/musculoskeletal-health/research/">Research</a>
        </li>
        <li data-label="education">
          <a rel="page" href="/expertise/musculoskeletal-health/education/">Education and Training</a>
        </li>
       
      </ul>
       </div>
     </div>
   </div> 
   
  <div class="expertise-detail" data-label="traumatic-brain">
     <span class="menu-header">Traumatic Brain Injury</span>
       <div class="summary">
          <p>Indiana University School of Medicine is recognized as a national leader in the research, diagnosis, treatment and rehabilitation of traumatic brain injuries and mild traumatic brain injuries, also known as concussions.</p>
       </div>
      <div class="row">
        <div class="col-md-6">
          <ul class="mm-menu" data-label="traumatic-brain">
            <li data-label="education">
              <a rel="page" href="/expertise/traumatic-brain-injury/education/">Education Program</a>
            </li>
            <li data-label="brain.research">
              <a rel="page" href="/expertise/traumatic-brain-injury/research/">Research</a>
            </li>
            <li data-label="clinical-trials">
              <a rel="page" href="/expertise/traumatic-brain-injury/clinical-trials/">Clinical Trials</a>
            </li>
          </ul>
        </div>
          <div class="col-md-6">
            <ul class="mm-menu">
          <li data-label="faq">
            <a rel="page" href="/expertise/traumatic-brain-injury/faq/">FAQ</a>
          </li>
          <li data-label="what-is-traumatic-brain-injury">
            <a rel="page" href="/expertise/traumatic-brain-injury/what-is-traumatic-brain-injury/">What is TBI?</a>
          </li>
          <li data-label="what-is-chronic-traumatic-encephalopathy/">
            <a rel="page" href="/expertise/traumatic-brain-injury/what-is-chronic-traumatic-encephalopathy/">What is CTE?</a>
          </li>
      
        </ul>
        </div>
      </div>
    </div>
       
    <div class="expertise-detail" data-label="global-health">
          <span class="menu-header">Global Health</span>
      <div class="summary">
          <p>IU School of Medicine is leader in global health offering care programs, research and training around the globe. Faculty and learners can participate in unparalleled opportunities particularly in Kenya through our robust, 30-year partnership.</p>
       </div>
      <div class="row">
        <div class="col-md-6">
          <ul class="mm-menu" data-label="global-health">
            <li data-label="global.education">
              <a rel="page" href="/expertise/global-health/education/">Education Programs</a>
            </li>
            <li data-label="global.research">
              <a rel="page" href="/expertise/global-health/research/">Research</a>
            </li>
            <li data-label="clinical">
              <a rel="page" href="/expertise/global-health/clinical/">Clinical Impact</a>
            </li>
          </ul>
        </div>
        <div class="col-md-6">
          <ul class="mm-menu" data-label="traumatic-brain">
        <li data-label="news-events">
          <a rel="page" href="/expertise/global-health/news-events/">News and Events</a>
        </li>
        
      </ul>
          </div>
        </div>
      </div>
     </div>

  
  </div>
</div>


