<div class="megamenu-panel" id="megamenu-about" data-target="about">
	<div class="bg row"></div>
	<div class="fg row">
		<div class="col-md-4 mm-left">
			<h2 class="menu-header">About IU School of Medicine</h2>
			<div class="pane">
				<ul class="arrow-bullets">
					<li><a href="/about/strategic-plan/">Strategic Plan</a></li>
					<li><a href="/about/mission-vision-values/">Mission, Vision and Core Values</a></li>
					<li><a href="/about/diversity/">Diversity</a></li>					
					<li><a href="/about/history/">School History</a></li>
					<li><a href="/about/awards-honors/">Honors and Awards</a></li>
					<li><a href="/about/learning-environment/">Learning Environment</a></li>
					<li><a href="/about/contacts/">Contacts</a></li>
					<li><a href="/about/faq/">FAQ</a></li>
				</ul>
			</div>
		</div>
		<div class="col-md-4 mm-center">
			<h2 class="menu-header">Policies &amp; Guidelines</h2>
			<div class="pane">
				<ul class="arrow-bullets">					
					<li><a href="/about/policies-guidelines/">Overview</a></li>
					<li><a href="/about/policies-guidelines/privacy-policy/">Privacy Policy</a></li>
					<li><a href="/about/policies-guidelines/industry-relations/">Industry Relations Policy</a></li>
					<li><a href="/about/policies-guidelines/emergency-response/">Emergency Response</a></li>
					<li><a href="/about/policies-guidelines/honor-code/">Honor Code</a></li>
				
				</ul>
			</div>
		</div>
		<div class="col-md-4 mm-right">
			<h2 class="menu-header">Leadership &amp; Administration</h2>
			<div class="pane">
				<ul class="arrow-bullets">
					<li><a href="/about/executive-leadership/">Executive Leadership</a></li>
          <li><a href="/about/executive-leadership/dean/">Dean's Office</a></li>
       		<li><a href="/about/executive-leadership/administrative-services/">Administrative Affairs</a></li>
					<li><a href="/about/executive-leadership/clinical-affairs/">Clinical Affairs</a></li>
					<li><a href="/about/executive-leadership/educational-affairs/">Educational Affairs</a></li>
					<li><a href="/about/executive-leadership/faculty-affairs/">Faculty Affairs</a></li>
					<li><a href="/about/executive-leadership/research-affairs/">Research Affairs</a></li>
          <li><a href="/about/executive-leadership/technology-affairs/">Technology Affairs</a></li>

				</ul>
			</div>
		</div>
	</div>
</div>


